# Hybrid mode example: Control plane.
services:
  iam-migrations:
    image: containers.intersystems.com/intersystems/iam:3.10
    command: bash -c "kong migrations bootstrap; kong migrations up; kong migrations finish"
    depends_on:
      - db
    environment:
      KONG_DATABASE: postgres
      KONG_PG_DATABASE: ${KONG_PG_DATABASE:-iam}
      KONG_PG_HOST: db
      KONG_PG_PASSWORD: ${KONG_PG_PASSWORD:-iam}
      KONG_PG_USER: ${KONG_PG_USER:-iam}
      KONG_CASSANDRA_CONTACT_POINTS: db
      ISC_IRIS_URL: IAM:${IRIS_PASSWORD}@host.docker.internal:80/api/iam/license
    restart: on-failure
    links:
      - db:db
  iam:
    image: containers.intersystems.com/intersystems/iam:3.10
    depends_on:
      - db
    environment:
      KONG_LOG_LEVEL: debug
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: '0.0.0.0:8001'
      KONG_ANONYMOUS_REPORTS: 'off'
      KONG_CASSANDRA_CONTACT_POINTS: db
      KONG_DATABASE: postgres
      KONG_PG_DATABASE: ${KONG_PG_DATABASE:-iam}
      KONG_PG_HOST: db
      KONG_PG_PASSWORD: ${KONG_PG_PASSWORD:-iam}
      KONG_PG_USER: ${KONG_PG_USER:-iam}
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_PORTAL: 'on'
      KONG_PORTAL_GUI_PROTOCOL: http
      KONG_PORTAL_GUI_HOST: 'localhost:8003'
      KONG_ADMIN_GUI_URL: http://localhost:8002
      KONG_VITALS: 'on'
      KONG_ADMIN_GUI_HIDE_KONNECT_CTA: 'on'
      ISC_IRIS_URL: IAM:${IRIS_PASSWORD}@host.docker.internal:80/api/iam/license

      KONG_ROLE: control_plane
      KONG_CLUSTER_SERVER_NAME: 'kong_clustering'
      KONG_CLUSTER_LISTEN: '0.0.0.0:8005 ssl'
      KONG_CLUSTER_TELEMETRY_LISTEN: '0.0.0.0:8006 ssl'
      KONG_CLUSTER_MTLS: 'shared'
      KONG_CLUSTER_CERT: /etc/kong/admin.crt
      KONG_CLUSTER_CERT_KEY: /etc/kong/admin.key
      KONG_LUA_SSL_TRUSTED_CERTIFICATE: /etc/kong/admin.crt

    # This IP needs to be changed to point at the docker host.
    extra_hosts:
        - "kong_clustering:host-gateway"
    links:
      - db:db
    ports:
      - target: 8001
        published: 8001
        protocol: tcp
      - target: 8002
        published: 8002
        protocol: tcp
      - target: 8003
        published: 8003
        protocol: tcp
      - target: 8004
        published: 8004
        protocol: tcp
      - target: 8005
        published: 8105
        protocol: tcp
      - target: 8006
        published: 8006
        protocol: tcp
    restart: on-failure

    volumes:
    - ./Certificates/admin.crt:/etc/kong/admin.crt
    - ./Certificates/admin.key:/etc/kong/admin.key

  db:
    image: postgres
    environment:
      POSTGRES_DB: ${KONG_PG_DATABASE:-iam}
      POSTGRES_PASSWORD: ${KONG_PG_PASSWORD:-iam}
      POSTGRES_USER: ${KONG_PG_USER:-iam}
    volumes:
      - 'pgdata:/var/lib/postgresql/data'
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${KONG_PG_USER:-iam}"]
      interval: 30s
      timeout: 30s
      retries: 3
    restart: on-failure
    stdin_open: true
volumes:
  pgdata:
